---
title: "Explore transcript types"
output: html_notebook
---


```{r}
library(dplyr)
library(data.table)
library(ggplot2)
library(gridExtra)
library(ggpubr)
#library(VennDiagram)

```



```{r}
txtbl <- fread('hg38c_txtable.tsv')
txtbl <- txtbl[chr!='chrM']
keepcodes <- unlist(strsplit("c=kjmno",''))
setnames(txtbl, c('tid', 'name', 'gbkey'), c('ref_id','txid','txtype'))
txtbl[, predicted:=grepl('^X', txid)]

## -- load a set
## loadtmap returns a list (tmap=dt, tnum=txcount)
file=files[3]
loadtmap <- function (file=NULL) {
  tmap <- fread(file)
  tnum <- nrow(tmap)
  tmap <- tmap[ref_id!='-' & class_code %in% keepcodes ]
  tmap[txtbl, `:=` (txid=i.txid, txtype=i.txtype, biotype=i.gene_biotype, 
                    gene_name=i.gene_name, predicted=i.predicted), on=.(ref_id) ]
  tmap <- tmap[!is.na(txid)]
  #'misc_RNA' is how GenBank labels 'ncRNA' transcripts from a 'protein_coding' gene
  stopifnot(all.equal(tmap[txtype=='misc_RNA'], 
                       tmap[grepl('^[NX]R_', txid) & biotype=='protein_coding'])==T)
  tmap[txtype=='misc_RNA', txtype:='ncRNA']
  ## contingency table: predicted x coding for matching 
  tmm <- unique(tmap[class_code=='=', .(txid, predicted, txtype)])
  tmm[,coding:=(txtype=='mRNA')]
  tmm$txtype <- NULL
  tc <- as.data.table(table(tmm[, .(predicted, coding)])) %>% setnames('N', 'count')
  tc[,`:=`(predicted=ifelse(predicted==T, "theoretical", "curated"), coding=ifelse(coding==T, 'coding', 'non-coding'))]

  list(td=tmm, tc=tc)
  
  #tpred <- as.data.table(table(tmm$predicted))
  #colnames(tpred) <- c('predicted', 'count')
  #tcod <- as.data.table(table(tmm$txtype))
  #colnames(tcod) <- c('coding', 'count')
  #tcod[, coding:=(coding=='mRNA')]
  #list(tmap=tmap, tnum=tnum, tcod=tcod, tpred=tpred)
}
```

```{r}
drawVenn <- function(s3, names=NULL, title=NULL) {
  if (!is.null(names)) names(s3) <- names
  #myCol <- c("#ABB5E890", "#E8ABB590", "#E280E290")
  myCol <- c("#4048E880", "#F84B4580", "#b240c280")
  #myEdgeCol <- c("#ABB5E8ff", "#E8ABB5ff", "#E280E2ff")
  myEdgeCol <- c("#a0a8ff", "#f88484", "#b2a0d2")
  mylcol <- c("#4048E8", "#E84B45ff", "#b040B0ff")
  vd <- venn.diagram(x=s3,
         #category.names = c("Long", "Short", "Hybrid"),
         #filename = "venn1_tm.png",
         filename = NULL,
         output=T,
         height = 2.3, 
         width = 2.3, 
         units = "in",
         dpi = 72,
         compression = "lzw",
         # Circles
        fill = myCol, lwd=1, lty='solid', col=myEdgeCol, #lwd = 2, lty = 'blank', 
         # Numbers
        cex = 0.75, fontface = "bold", fontfamily = "sans",
        # Set names
        cat.cex = 0.82, cat.fontface = "bold",
        cat.col = mylcol,
        cat.default.pos = "outer",
        cat.pos = c(-37, 37, 128),
        cat.dist = c(0.098, 0.098, 0.1),
        cat.fontfamily = "sans",
        rotation = 1,
        margin = 0.12
  )
  gt <-  gTree(children=vd)
  #gtcod <- addGrob(gtcod, linesGrob(x=c(0.01, 0.99, 0.99, 0.01, 0.01),
  #         y=c(0.01, 0.01, 0.99, 0.99, 0.01),
  #         gp=gpar(lwd=0.1)) )
  if (!is.null(title)) 
    return(arrangeGrob(grobs=list(gt,grid.text(title, y=1.6, gp=gpar(col="black", cex=0.9)) ), 
                       nrow=2, ncol=1, heights=c(18,1)))
  return(gt)
}

```


```{r}
#must be in this order: short, long, mix
files <- c('SRR16071313_short.tmap', 'SRR16071311_long.tmap', 'SRR16071313_SRR16071311_mix.tmap')
showLegend=T
genbarPlots <- function(files=NULL, showLegend=T) {
  sd <- loadtmap(files[1])
  ld <- loadtmap(files[2])
  md <- loadtmap(files[3])
  
  dtc <- rbindlist(list(sd$tc[, assembly:='Short'], ld$tc[, assembly:='Long'], md$tc[, assembly:='Hybrid']))
  dtc$assembly <- factor(dtc$assembly, levels=c('Long', 'Short', 'Hybrid'))
  dtc[, yp:=cumsum(count), by=.(assembly, coding)]
  
  #dtc[, cvar:=ifelse(predicted=='theoretical', coding, as.character(assembly)) ]
  dtc[, cvar:=ifelse(predicted=='theoretical', predicted, as.character(assembly)) ]
  dtc$cvar <- factor(dtc$cvar, levels=c('theoretical', 'Long', 'Short', 'Hybrid'))
  ylim=c(0, max(dtc$yp)+2000)
  #colors=c('Long'="#b4bafd", 'Short'= "#ff9b9b", 'Hybrid'="#d9aff0", 'non-coding'="#b0e8b0", 'theoretical'="#f0f070")
  #colors=c('Long'="#b4bafd", 'Short'= "#ff9b9b", 'Hybrid'="#d9aff0", 'theoretical'="#f0f070")  "#70e070")
  colors=c('theoretical'="#a0b0a0", 'Long'="#4040FF", 'Short'= "#FF4040", 'Hybrid'="#A040A0")
  gg <- ggplot(dtc[order(assembly, coding, -count)], aes(fill=cvar, y=count, x=coding)) +
    geom_bar(position="stack", stat="identity", width = 0.8) + # ggtitle("protein coding status")+
    scale_fill_manual(values=colors, labels = c("  RefSeq predicted           ", "", "", "  RefSeq curated")) +
    facet_grid(~ assembly) +
    #geom_label(data=subset(dmall, yl>0), aes(label=yp, y=yl, fill=cvar,  hjust=hj), 
    #           label.size=NA, vjust=0.4, color="black", size=3.2, show.legend = F)+
    geom_text(data=subset(dtc, predicted=='theoretical'), aes(label=yp, y=yp), vjust=-0.35, size=3.5) +
      scale_color_manual(guide="none")+
    coord_cartesian(ylim = ylim) +
    scale_y_continuous(expand = expansion(add=c(0,0)), breaks=seq(0, 20000, 5000)) +
    theme_bw() +xlab(NULL) + ylab('transcripts')
  bgcol="#F8F8F8"
  if (showLegend) {
    gg <- gg+theme( panel.border = element_blank(), 
          axis.line = element_line(colour = "gray80"), legend.key.size = unit(1,"line"),
          panel.background = element_rect(fill=bgcol), strip.text.x = element_text(size=11, face="bold"),
          panel.grid.minor = element_blank(), legend.position = "bottom", legend.title = element_blank(),
          strip.background = element_rect(color=bgcol, fill=bgcol, size=1.5), legend.spacing.x = unit(0.04, 'in') )
  } else {
    gg <- gg+theme( panel.border = element_blank(), 
          axis.line = element_line(colour = "gray80"), strip.text.x = element_text(size=11, face="bold"),
          panel.background = element_rect(fill=bgcol),
          panel.grid.minor = element_blank(), legend.position = "none", legend.title = element_blank(),
          strip.background = element_rect(color=bgcol, fill=bgcol, size=1.5) )
  }
}
```


```{r}
{
  dpred$assembly <- factor(dpred$assembly, levels=c('Long','Short', 'Hybrid'))
  dpred[, cvar:=paste0(substr(assembly, start=1, stop=1), ifelse(predicted, 'T', 'F')) ]
  dpred[order(count), yp:=cumsum(count), by=assembly] #[predicted==F, yp:=yp-600]

  dcod <- rbindlist(list(sd$tcod[, assembly:='Short'], ld$tcod[, assembly:='Long'], md$tcod[, assembly:='Hybrid']))
  dcod$assembly <- factor(dcod$assembly, levels=c('Long', 'Short', 'Hybrid'))
  dcod[, cvar:=paste0(substr(assembly, start=1, stop=1), ifelse(coding, 'F', 'T')) ]
  dcod[order(count), yp:=cumsum(count), by=assembly]
  
 
  
  dmcod <-  copy(dcod)
  setnames(dmcod, 'coding', 'status')
  dmcod$type <- 'non-coding'
  dmpred <-  copy(dpred)
  setnames(dmpred, 'theoretical', 'status')
  dmpred$type <- 'predicted'
  dmall <- rbindlist(list(dmcod, dmpred))
  dmall[type=='non-coding' & status==F, cvar:='nc']
  dmall[type=='theoretical' & status==T, cvar:='pred']
  dmall$cvar <- factor(dmall$cvar, levels=c('LF', 'SF', 'HF', 'nc', 'pred' ))
  dmall$hj <- 0.5
  dmall$yl <- dmall$yp
  
  ylim=c(0, max(dmall$yl)+1000)
  #dmall[ type=='predicted' & ! cvar %in% c('nc','pred'), yl:=0]
  #dmall[ type=='non-coding' & ! cvar %in% c('nc','pred'), yl:=yl-2000]
  #dmall[ type=='non-coding' & ! cvar %in% c('nc','pred'), hj:=-0.34]
    
  colors=c('LF'="#b4bafd", 'SF'= "#ff9b9b", 'HF'="#d9aff0", 'nc'="#b0e8b0", 'pred'="#f0f070")
  #colors=c('LF'="#9090ff", 'SF'= "#ff9090", 'HF'="#ff70ff", 'nc'="#b6d864", 'pred'="#f4e24f")
  #colors=c('LF'="#9090ff", 'SF'= "#ff7B75", 'HF'="#ef70ff", 'nc'="#b6d864", 'pred'="#f4e24f")
    #colors=c('SF'= "#e34031", 'LF'="#3758f3", 'HF'="#c062c0", 'nc'="#674a5f", 'pred'="#3a722c")
    #colors=c('SF'= "#e34031", 'LF'="#3758f3", 'HF'="#c062c0", 'nc'="#5a5a5a", 'pred'="#5a924c")
    
  #gcod <- 
    #ggplot(dcod, aes(fill=cvar, y=count, x=assembly)) +
 gg <-     
  ggplot(dmall[order(yp)], aes(fill=cvar, y=count, x=type)) +
    geom_bar(position="stack", stat="identity", width = 0.8) + # ggtitle("protein coding status")+
    scale_fill_manual(values=colors, labels = c("Long", "Short", "Hybrid", "non-coding", "theoretical")) +
    facet_grid(~ assembly) +
    #geom_label(data=subset(dmall, yl>0), aes(label=yp, y=yl, fill=cvar,  hjust=hj), 
    #           label.size=NA, vjust=0.4, color="black", size=3.2, show.legend = F)+
    geom_text(aes(label=yp, y=yl), vjust=-0.4) +
      scale_color_manual(guide="none")+
    coord_cartesian(ylim = ylim) +
    scale_y_continuous(expand = expansion(add=c(0,0)), breaks=seq(0, 20000, 5000)) +
    theme_bw() + xlab(NULL) + ylab('transcripts') +
    theme( panel.border = element_blank(), 
          axis.line = element_line(colour = "gray80"),
          panel.grid.minor = element_blank(), legend.title = element_blank(),
          strip.background = element_rect(color="white", fill="white", size=1.5)
     )
 
 ## output should be 596x188 px, i.e. 8.27 x 2.61 in
 #gg    
 #ggsave(gg, file="my_plot_chart.svg", width=6.6, height=2.2, device="svg")
 #l=as.numeric(charToRaw(startLetter))+1
 #vlabels=c(rawToChar(as.raw(l)), rawToChar(as.raw(l+1)), rawToChar(as.raw(l+2)))
 #vnds <- ggarrange(vcod, vncod, vpred, labels=vlabels, vjust=1.4, ncol=3, nrow=1)
 #if (startLetter=='A') 
 #    return(ggarrange(gg, vnds, labels=startLetter, vjust=1.4, ncol=1, nrow=2, widths=c(1,0.5)))

 #ggall <- 
 #ggarrange(linesGrob(x=c(0.01, 0.99), y=c(0.99, 0.99), gp=gpar(col="gray60", lwd=0.4)), 
#        ggarrange(gg, vnds, labels=startLetter, vjust=1.4, ncol=1, nrow=2, widths=c(1,0.5)),
#        nrow=2, ncol=1, heights=c(0.01, 1))
 
 #ggsave(ggall, file="0_ggarr.svg", width=6.6, height=4.2, device="svg")
 return(gg)
}
```


```{r}
#library(ggpattern)

options(repr.plot.width = 10, repr.plot.height = 6)
#overrideTriple =  T
tmapfiles <- c('SRR16071313_short.tmap', 'SRR16071311_long.tmap', 'SRR16071313_SRR16071311_mix.tmap')

g1 <- genbarPlots(tmapfiles)

#ggsave(g1, file="1_ggarr.svg", width=6.6, height=4.2, device="svg")


g2 <- genbarPlots(c('all_merged_short.tmap', 'all_merged_long.tmap', 'all_merged_mix.tmap'), F)

#ggsave(g2, file="2_ggarr.svg", width=6.6, height=4.2, device="svg")


fig <- ggarrange(g1, g2, labels=c("A", "B"), ncol=1, nrow = 2, heights=c(1.1, 1)) +
  theme(plot.margin = margin(t=0.4, r=0, l=0, unit="cm"))


ggsave(fig, file="fig7_pred_nc.svg", width=5.2, height = 6.2, device="svg")

#fig <- ggarrange(g1$gpred, g1$gcod, g2$gpred, g2$gcod, labels=c("A", "B", "C", "D"),
#                 vjust = 0.3, ncol=2, nrow = 2)+theme(plot.margin = margin(t=0.4, unit="cm"))
fig


```


